### ISSUE TITLE
I think Netflix changed something

### ISSUE THREAD

**Issue by fabrebatalla18** [shirt-dev/netflix-international#1]
Now this extension dont show all dubs/subs anymore, for example: Sranger Things 1x01:
https://www.netflix.com/title/80057281

**Comment by shirt-dev** [comment]
I believe Netflix has started to limit the `showAllSubDubTracks` parameter in EU regions.

**Comment by shirt-dev** [comment]
I've pushed an update with a language selector in the extension options. Unfortunately, only one language can be selected at a time due to a server side restriction.

**Comment by fabrebatalla18** [comment]
> I've pushed an update with a language selector in the extension options. Unfortunately, only one language can be selected at a time due to a server side restriction.

Can you add "es-ES" ("es" its fro latinoamerican spanish), and maybe pt-br and other variants, or just some option to add custom language to user can put any language, please?

**Comment by shirt-dev** [comment]
When you put in es, it should give you access to both Latin American and European Spanish. I will do some additional testing.

**Comment by fabrebatalla18** [comment]
Yes, but if you put "es" then netflix will play automatically everytime the latinamerican spanish, so if you want to play european spanish you need to change all time, and exist other regional languages like catalan, basque or galician what you dont put in the list, for example, then its more easy if you allow users to put some custom language (in addition to the default list)

**Comment by shirt-dev** [comment]
Ah yes, I see what you mean now. I will update it, thanks!

**Comment by shirt-dev** [comment]
Source code has been updated, the chrome web store listing is under review already and I cannot submit a new version until the review is done, so until then you may need to sideload the extension.

**Comment by shirt-dev** [comment]
Chrome Web Store is updated.
