### ISSUE TITLE
Blackscreen on Chromium Browsers on Mac

### ISSUE THREAD

**Issue by heismauri** [shirt-dev/netflix-international#2]
Hi there, I've been using this ext for a long time on my Windows PC and sadly it stopped working on my Mac PC. I am currently running macOS Catalina 10.15.7, and I tested it on Brave and Google Chrome. Both gave me a black screen, but when using [the extension](https://github.com/truedread/netflix-1080p) this is based on I do not get a black screen.

SS:
![Screen Shot 2022-09-11 at 3 37 41 PM](https://user-images.githubusercontent.com/47569205/189543689-692528e0-8129-404e-9644-232e2775fe28.png)

**Comment by shirt-dev** [comment]
It's likely due to the AV1 profile, I'll have to make a new release without AV1 turned on for MacOS.

**Comment by shirt-dev** [comment]
This should be fixed as of the latest commit, I removed AV1 support due to a number of issues.
