### ISSUE TITLE
Low audio bitrate on Microsoft Edge DDPlus 5.1 option

### ISSUE THREAD

**Issue by Phoenomenal** [shirt-dev/netflix-international#3]
Hello!

I am on Microsoft Edge browser and noticed that  there is always lowest audio bitrate when on 5.1 audio like in a pictures below (ctrl+alt+shift+d  and ctrl+alt+shift+s show these statistics)  The thing is you cant choose audio bitrate from this menu ctrl+alt+shift+s   only video bitrate can be altered this way.    Can you make it that there is highest audio bitrate  by default (like in  netflix-4K-DDplus extension  https://github.com/lkmvip/netflix-4K-DDplus)  ?
![Screenshot_1](https://user-images.githubusercontent.com/68902338/197407788-8af1487b-1308-4ba3-b57e-77e7771e33c0.png)
![Screenshot_2](https://user-images.githubusercontent.com/68902338/197407791-c6318a94-9ab0-4cf4-8017-b10641a903df.png)

**Comment by shirt-dev** [comment]
I'll need to figure out how that extension is switching the bitrate, this is currently a low priority as this only affects Edge users.

**Comment by shirt-dev** [comment]
Should be resolved as of 3435e4d1368ac84bfc884c8b8330083d6aa8aa28.
