### ISSUE TITLE
Add option to disable H264 main (AVC) profile or add an option to choose AV1 as default profile globally 

### ISSUE THREAD

**Issue by Antivan28** [shirt-dev/netflix-international#4]
Hi,

I wonder  does it possible to add an option to disable  h264 main profile (AVC) ?     The existing option disable h264HPL disable only AVCHIGH codec  and reverts to AVC if check this option on Microsoft Edge browser.   I want to enable AV1 profile on microsoft edge.
The situation is different on Google Chrome  where av1 profile  is by default so in that browser you can basically choose whatever profile you want by checking/unchecking options.   On Edge its only AVC High (H264HPL)   or AVC because there is no option to disable AVC (h264 main)  in extension right now. 

Or since many shows on Netflix dont support AV1 at the moment (just tested on Google Chrome)  maybe  it worth making an option to choose  which profile will be default one globally (preferably AV1 option as default since its newest and better codec)   and if show dont support that profile (like with AV1) than to revert on other codec  (avс, avchigh  or vp9 whichever will not be checked  as disabled in options )   So if  that option is present you can basically enable whatever profile you want on any browser which is awesome.   ?

**Comment by shirt-dev** [comment]
Since Microsoft Edge relies on Playready DRM for Netflix, unfortunately neither of these requests are possible. I would recommend using a browser with Widevine DRM such as Chrome to get these features.
