### ISSUE TITLE
Bug :   Failed to find patch: "Select highest audio bitrate 1"   

### ISSUE THREAD

**Issue by Phoenomenal** [shirt-dev/netflix-international#5]
Hi.

For a few weeks already see this message via window pop up each time when open netflix.com website.  The extension is still working but if using microsoft edge browser 5.1 audio automatically playing lowest bitrate unfortunately.  

To reproduce the eroor simply open netflix website while netlix international extension is enabled  on any browser.

Can you please fix it so no more message shown every time Netflix website load  ?

<img width="388" alt="Screenshot_2" src="https://user-images.githubusercontent.com/68902338/224514534-c984adf0-df28-429c-bbfb-3b853ccbe68c.png">

**Comment by shirt-dev** [comment]
This should be fixed as of 24b0d31ab550548c618164cc5f5fe5177f7af7e5.
