### ISSUE TITLE
On Edge videos wont load when option : Use DDPLUS is checked.

### ISSUE THREAD

**Issue by Antivan28** [shirt-dev/netflix-international#6]
Hi there,  on Edge browser there is a bug when option  Use Dolby Digital Plus is checked there is an error popup window each time netflix page is refreshed whick says:  Failed to find patch: Select highest audio bitrate 2 .    And as a result all videos wont load util this option is unchecked and no error pop up.   But in that case Netflix use inferior HE-AAC codec for audio.

**Comment by wft44maqb** [comment]
Same.

![image](https://github.com/shirt-dev/netflix-international/assets/86122516/d472222a-81ee-49a5-9e6b-c5a9c0dbe1be)

![image](https://github.com/shirt-dev/netflix-international/assets/86122516/e003fc4d-3231-4e6a-9fcd-e63a67618ebd)

**Comment by shirt-dev** [comment]
I'll look into it.

**Comment by shirt-dev** [comment]
Unfortunately Netflix changed some stuff on the backend and I can't figure out how to fix it. I am closing this issue as not implemented for now. PRs are welcome to restore this functionality.
